### ISSUE TITLE
Redirection not working

### ISSUE THREAD

**Issue by DraXus** [ackness/GazeFlow_demo#1]
I'm running the redirection demo using the Google Colab, but I'm always getting the same image for original and redirected images no matter what values I tried.

Sharing some examples:

![Screenshot 2021-09-10 160806](https://user-images.githubusercontent.com/2436/132867301-adb0abbb-de18-49ef-b64e-5035b7376544.png)
![Screenshot 2021-09-10 160902](https://user-images.githubusercontent.com/2436/132867302-a99961a9-181c-4376-ba98-551b3a7f68eb.png)
![Screenshot 2021-09-10 160629](https://user-images.githubusercontent.com/2436/132867296-117124c5-1f91-4615-afa6-d10e9b14b890.png)
![Screenshot 2021-09-10 160649](https://user-images.githubusercontent.com/2436/132867298-f60d533f-aceb-42e2-a8ef-14f54f495000.png)
![Screenshot 2021-09-10 160736](https://user-images.githubusercontent.com/2436/132867300-e1431c02-e945-42bc-9fff-7dd759069604.png)

**Comment by ackness** [comment]
Hi, I am sorry for that, I forget that I changed the name of checkpoint before.

![image](https://user-images.githubusercontent.com/19150500/132944386-c4ba438a-f38f-4d7e-8ec7-10acbc278f34.png)

It should be `eth-xgaze-redirection-gazeflow-ckpt.zip`:

![image](https://user-images.githubusercontent.com/19150500/132944367-b9b03930-f95d-4a75-8421-c115c10bfc35.png)


Now it works:

![image](https://user-images.githubusercontent.com/19150500/132944513-1c6b0647-241b-45f4-a1cd-c0a5ee22d86e.png)

![image](https://user-images.githubusercontent.com/19150500/132944528-b35c6df8-0a3d-4aa2-b32d-78f691fb69c6.png)

![image](https://user-images.githubusercontent.com/19150500/132944537-48646ff7-aa12-478a-a01d-9624c3d4ee98.png)
